language: scala
scala: 2.12.8

# make sure to fetch enough commits, so that git describe still works
git:
  depth: false


before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install adopt@1.8.192-12 && jabba use $_ && java -version

jobs:
  include:
    - script:
      - bin/scalafmt --test
      - sbt test headerCheck test:headerCheck
#   - stage: whitesource-master
#     script: git branch -f "$TRAVIS_BRANCH" && git checkout "$TRAVIS_BRANCH" && sbt whitesourceCheckPolicies whitesourceUpdate
#   - stage: whitesource-release
#     script: git branch -f "$TRAVIS_BRANCH" && git checkout "$TRAVIS_BRANCH" && sbt whitesourceCheckPolicies whitesourceUpdate
    - stage: publish
      script: sbt +publish
    - stage: techhub-ping
      script: curl -I https://ci.lightbend.com/job/techhub-publisher/build?token=$TECH_HUB_TOKEN

stages:
  - name: test
    if: NOT tag =~ ^v
# - name: whitesource-master
#   if: repo = playframework/play-grpc AND branch = master AND type = push
# - name: whitesource-release
#   if: repo = playframework/play-grpc AND tag =~ ^v
  - name: publish
    if: repo = playframework/play-grpc AND tag =~ ^v
  - name: techhub-ping
    if: repo = playframework/play-grpc AND tag =~ ^v

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.jabba/jdk
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete

notifications:
  email:
    on_success: never
