language: scala
scala: 2.12.13

# make sure to fetch enough commits, so that git describe still works
git:
  depth: false

env:
  global:
  # encrypt with: travis encrypt --com --repo playframework/play-grpc  WHITESOURCE_PASSWORD=...
  - secure: "P+tk+59lSGZSWcsY/O6jeEKpZlXWawy3tLfGxAqs0nw/mf7OMrBVkTMnt7tcnb9ggMHIThO5CQiu+dZ4PwSY1hFFua22XVeqBQb6SWwc36ea5GY4hSHE/nHq51nShX45f3wjaHZ5rjT/jwRYmRBwvmIVFUsAExABv8YoG/I+EeIJ+JRBSAmGNPuxQ/+OUk7qAz1VrP0cUW7t68Cs66c5J+iDvQ8/UKb7u9XU43i7eoB3SnCJdyFCvAXzGkHOf3Yph0rn2dmEFIIZIxoLBx81DYQh+5efNT8pcyK5kviWIGB0XeQMTfIY3NTbaS8K8E7OLZ37Hd75c29ZHIX/7cIQOZRnnhlI2z1mCvBj6IuYnFpL3EJO+mccvTKMKuNhHmCWzTKV85wLk+1JB31ZH+mV9+hjiMY4ChiwFIbJZvBLRrHL/NqwQ0GPRQf/6GrBVydEvv2uWIB31KOnhwnie25Lwq0ptxXAzUPiwQnNJTFkbWHnrhxkabgVAKE6128SNUzUWK64c/tCjLEK8WS9WEPxVaQq1jXIYPbDadaz8yB6n9kDkg1jLkCwKCZsMumQGb/JQbhPNkYBpZG3A5WlGrAqqRU5KGbvXSlzsXi3/n06xSMaJBbZAAGY9+F9jnnYta2LxNpMcAyjLet+nXr8d/F/k59WgWcqSCuzuBjMbNtoQGI="
  matrix:
    - TRAVIS_JDK=8
    - TRAVIS_JDK=11

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "$_" && java -Xmx32m -version
script: sbt headerCheck test:headerCheck scalafmtCheckAll scalafmtSbtCheck test paradox ++2.13.1 test

jobs:
  include:
    - stage: publish
      script: sbt ++2.12.11 publish ++2.13.1 "project play-grpc-generators; set publish/skip := true; project play-grpc" publish
    - stage: techhub-ping
      script: curl -I https://ci.lightbend.com/job/techhub-publisher/build?token=$TECH_HUB_TOKEN
    - stage: whitesource
      script: git branch -f "$TRAVIS_BRANCH" && git checkout "$TRAVIS_BRANCH" && sbt whitesourceCheckPolicies whitesourceUpdate


stages:
  - name: test
    if: NOT tag =~ ^v
  - name: publish
    if: repo = playframework/play-grpc AND tag =~ ^v
  - name: techhub-ping
    if: repo = playframework/play-grpc AND tag =~ ^v
  - name: whitesource
    if: repo = playframework/play-grpc AND ((branch = master AND type != pull_request) OR tag =~ ^v)

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.jabba/jdk
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete

notifications:
  email:
    on_success: never
